apiVersion: v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    name: voting-app-deploy
    app: voting-app
spec:
  replicas: 1
  selector:
    matchlabels:
      name: redis-pod
    app: voting-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: voting-app
    spec:
      containers:
      - name: redis
        image: kodekloud/examplevotingapp_redis:v1
        ports:
        - containerPort: 6379