apiVersion: v1
kind: Service
metadata:
  name: results-app-service
  labels:
    name: results-app-service
    app: voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    name: results-app-pod
    app: voting-app
