apiVersion: v1
kind: Deployment
metadata:
  name: results-deploy
  labels:
    name: results-app-pod
    app: voting-app
spec:
  replicas: 1
  selector:
    matchlabels:
      name: results-deploy
      app: voting-app
  template:
    metadata:
      name: results-app-pod
      labels:
        name: results-app-pod
        app: voting-app
    spec:
      containers:
      - name: results-app
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80