apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: voting-app
spec:
  containers:
  - name: voting
    image: kodekloud/examplevotingapp_vote:v1
    ports:
      - containerPort: 80
