apiVersion: v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    name: worker-app-pod
    app: voting-app
spec:
  replicas: 1
  selector:
    matchlabels:
      name: worker-deploy
      app: voting-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: voting-app
    spec:
      containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker:v1